# Generated by Django 4.0.5 on 2022-06-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=500)),
                ('Date', models.DateField()),
                ('Amount', models.FloatField()),
                ('No_of_persons', models.IntegerField(default=1)),
                ('E_name', models.CharField(max_length=200)),
            ],
        ),
    ]
